services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  app:
    image: "node:lts-slim"
    env_file:
      - .env
    command:
      - /bin/sh
      - "-c"
      - "npm install && npm start"
    working_dir: /home/node/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - ./mini-crm-back:/home/node/app

volumes:
  mongo-data:
